# A3DShell Configuration
# Generated: 2025-11-12 21:26:56

[GENERAL]
SIMULATION_NAME = quick_test_20m
START_DATE = 2023-10-01T00:00:00
END_DATE = 2023-10-02T23:59:00

[INPUT]
EAST_epsg2056 = 645000.0
NORTH_epsg2056 = 115000.0
altLV95 = 1500.0
USE_SHP_ROI = false
ROI = 500
BUFFERSIZE = 5000

[OUTPUT]
OUT_COORDSYS = CH1903+
GSD = 20.0
GSD_ref = 2.0
DEM_ADDFMTLIST =
MESH_FMT = vtu

[MAPS]
PLOT_HORIZON = false

[A3D]
USE_GROUNDEYE = false
USE_LUS_TLM = false
LUS_PREVAH_CST = 11500
DO_PVP_3D = false
PVP_3D_FMT = vtu
SP_BIN_PATH = input/bin/snowpack
