# A3Dshell Configuration
# Generated: 2025-11-19 14:48:40

[GENERAL]
SIMULATION_NAME = test_v2_3
START_DATE = 2023-10-01T00:00:00
END_DATE = 2023-10-31T23:59:00

[INPUT]
EAST_epsg2056 = 645000.0
NORTH_epsg2056 = 115000.0
altLV95 = 1500.0
USE_SHP_ROI = true
ROI_SHAPEFILE = config/shapefiles/roi_drawn.shp
BUFFERSIZE = 10000

[OUTPUT]
OUT_COORDSYS = CH1903+
GSD = 10.0
GSD_ref = 2.0
DEM_ADDFMTLIST =
MESH_FMT = vtu
MASK_DEM_TO_POLYGON = false
MASK_LUS_TO_POLYGON = true

[MAPS]
PLOT_HORIZON = false

[A3D]
USE_GROUNDEYE = false
USE_LUS_TLM = true
DO_PVP_3D = false
PVP_3D_FMT = vtu
SP_BIN_PATH = snowpack
