# A3Dshell Configuration
# Generated: 2025-11-18 09:02:20

[GENERAL]
SIMULATION_NAME = Test
START_DATE = 2023-10-01T00:00:00
END_DATE = 2024-06-01T23:59:00

[INPUT]
EAST_epsg2056 = 645000.0
NORTH_epsg2056 = 115000.0
altLV95 = 1500.0
USE_SHP_ROI = true
ROI_SHAPEFILE = config/shapefiles/roi_drawn.shp
BUFFERSIZE = 10000

[OUTPUT]
OUT_COORDSYS = CH1903+
GSD = 20.0
GSD_ref = 2.0
DEM_ADDFMTLIST =
MESH_FMT = vtu

[MAPS]
PLOT_HORIZON = false

[A3D]
USE_GROUNDEYE = false
USE_LUS_TLM = false
LUS_PREVAH_CST = 11500
DO_PVP_3D = false
PVP_3D_FMT = vtu
SP_BIN_PATH = snowpack
