[General]
BUFFER_SIZE = 370
BUFF_BEFORE	= 1.5

[Input]
COORDSYS	= CH1903
TIME_ZONE	= 1
#IMIS network database input -> IMIS plugin
METEO = IMIS
DBNAME          = sdbo.wd.op 
DBUSER          = snowpack_app
DBPASS          = Plouf_Plouf
USE_CONNECTION_STRING = TRUE
DBPORT = 1521
DBSID = sdbo
METEOPATH = ./input/meteo

#* - USEANETZ: use ANETZ stations to provide precipitations for normal IMIS stations. Almost each IMIS station is associated with one or two ANETZ stations and does a weighted average to get what should be its local precipitations if no local precipitation has been found (either nodata or 0).
# * - USE_IMIS_PSUM: if set to false (default), all IMIS precipitation will be deleted (since IMIS stations don't have heated rain gauges, their precipitation measurements are not good in winter conditions). If set to true, the precipitation measurements will be accepted from IMIS stations. In this case, it is strongly advised to apply the filter FilterUnheatedPSUM to detect snow melting in the rain gauge. ANETZ stations are unaffected (their precipitation is always used).
# i * - USE_SNOWPACK_PSUM: if set to true, the SNOWPACK simulated Snow Water Equivalent from the database will be used to compute PSUM. Data gaps greater than 3 hours on SWE will lead to u
#It is possible to use both USE_IMIS_PSUM and USE_SNOWPACK_PSUM to create composite PSUM (from SNOWPACK in the snow season and from IMIS otherwise).
#In such a case, as soon as SNOWPACK SWE > 0, all previous PSUM data will be deleted (ie those potentially coming from IMIS_PSUM). But if there is no SNOWPACK data, the IMIS measurements will be kept
#USEANETZ=FALSE
USE_IMIS_PSUM=TRUE
USE_SNOWPACK_PSUM=TRUE
# need to create ISWR field
ISWR::create = ISWR_ALBEDO

[Output]
COORDSYS	= CH1903
TIME_ZONE 	= 1

GRID2D		= ARC
GRID2DPATH	= ./output

METEO		= SMET
METEOPATH	= ./output

[Filter]
TIME::filter1     = suppr
TIME::arg1::cleanup = true

[Generators]
# generators only for already existing fields
# values used by the ISWR_albedo generator
; static const double 	soil_albedo = .23
; static const double 	snow_albedo = .85
; static const double 	snow_thresh = .1
; ISWR::generators = CST
; ISWR::Cst::value = 0.85
ISWR::generators = ISWR_ALBEDO
;ISWR::generators = clearSky_SW